package dev.barcodeworkbench.core.model

/**
 * The launch symbology table.
 *
 * Extending the app to another of libzint's 50-plus symbologies means adding one
 * entry here. Screens, pickers, validation and export all read from this
 * registry, so none of them need to change.
 *
 * All [SymbologySpec.zintSymbolId] values below were verified against libzint
 * 2.16 during the Phase 1 spike.
 */
object SymbologyRegistry {

    private val CODE39_CHARS = CharsetRule.Chars(
        allowed = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-. \$/+%",
        description = "Digits, A-Z uppercase, and - . space \$ / + %",
    )

    private val CODABAR_CHARS = CharsetRule.Chars(
        allowed = "0123456789-\$:/.+ABCD",
        description = "Digits, - \$ : / . + and A-D as start/stop",
    )

    val all: List<SymbologySpec> = listOf(
        // ---- Matrix ----
        SymbologySpec(
            id = SymbologyId.QR_CODE,
            displayName = "QR Code",
            zintSymbolId = 58,
            zintConstantName = "BARCODE_QRCODE",
            readerFormat = "QR_CODE",
            dimension = Dimension.MATRIX,
            category = Category.GENERAL,
            charsetRule = CharsetRule.Unicode,
            lengthRule = LengthRule.UpTo(4296),
            checkDigit = CheckDigitBehaviour.NONE,
            supportsGs1 = true,
            supportsEci = true,
            supportsStructuredAppend = true,
            supportsCodesetEscapes = false,
            sampleValue = "https://example.com",
        ),
        SymbologySpec(
            id = SymbologyId.MICRO_QR,
            displayName = "Micro QR Code",
            zintSymbolId = 97,
            zintConstantName = "BARCODE_MICROQR",
            readerFormat = "MICRO_QR_CODE",
            dimension = Dimension.MATRIX,
            category = Category.GENERAL,
            charsetRule = CharsetRule.Unicode,
            lengthRule = LengthRule.UpTo(35),
            checkDigit = CheckDigitBehaviour.NONE,
            supportsGs1 = false,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "MQR",
            notes = "Much smaller capacity than QR; intended for tight spaces.",
        ),
        SymbologySpec(
            id = SymbologyId.RMQR,
            displayName = "Rectangular Micro QR",
            zintSymbolId = 145,
            zintConstantName = "BARCODE_RMQR",
            readerFormat = "RMQR_CODE",
            dimension = Dimension.MATRIX,
            category = Category.GENERAL,
            charsetRule = CharsetRule.Unicode,
            lengthRule = LengthRule.UpTo(361),
            checkDigit = CheckDigitBehaviour.NONE,
            supportsGs1 = true,
            supportsEci = true,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "rMQR payload",
        ),
        SymbologySpec(
            id = SymbologyId.DATA_MATRIX,
            displayName = "Data Matrix",
            zintSymbolId = 71,
            zintConstantName = "BARCODE_DATAMATRIX",
            readerFormat = "DATA_MATRIX",
            dimension = Dimension.MATRIX,
            category = Category.INDUSTRIAL,
            charsetRule = CharsetRule.AnyByte,
            lengthRule = LengthRule.UpTo(2335),
            checkDigit = CheckDigitBehaviour.NONE,
            supportsGs1 = true,
            supportsEci = true,
            supportsStructuredAppend = true,
            supportsCodesetEscapes = false,
            sampleValue = "DM payload",
        ),
        SymbologySpec(
            id = SymbologyId.AZTEC,
            displayName = "Aztec Code",
            zintSymbolId = 92,
            zintConstantName = "BARCODE_AZTEC",
            readerFormat = "AZTEC",
            dimension = Dimension.MATRIX,
            category = Category.GENERAL,
            charsetRule = CharsetRule.AnyByte,
            lengthRule = LengthRule.UpTo(3832),
            checkDigit = CheckDigitBehaviour.NONE,
            supportsGs1 = true,
            supportsEci = true,
            supportsStructuredAppend = true,
            supportsCodesetEscapes = false,
            sampleValue = "Aztec payload",
        ),
        SymbologySpec(
            id = SymbologyId.PDF417,
            displayName = "PDF417",
            zintSymbolId = 55,
            zintConstantName = "BARCODE_PDF417",
            readerFormat = "PDF_417",
            dimension = Dimension.MATRIX,
            category = Category.LOGISTICS,
            charsetRule = CharsetRule.AnyByte,
            lengthRule = LengthRule.UpTo(1850),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = true,
            supportsEci = true,
            supportsStructuredAppend = true,
            supportsCodesetEscapes = false,
            sampleValue = "PDF417 payload",
            notes = "Wide aspect ratio; the viewer will suggest landscape.",
        ),
        SymbologySpec(
            id = SymbologyId.MICRO_PDF417,
            displayName = "MicroPDF417",
            zintSymbolId = 84,
            zintConstantName = "BARCODE_MICROPDF417",
            readerFormat = "MICRO_PDF_417",
            dimension = Dimension.MATRIX,
            category = Category.LOGISTICS,
            charsetRule = CharsetRule.AnyByte,
            lengthRule = LengthRule.UpTo(250),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = true,
            supportsEci = true,
            supportsStructuredAppend = true,
            supportsCodesetEscapes = false,
            sampleValue = "MicroPDF",
        ),
        SymbologySpec(
            id = SymbologyId.DOTCODE,
            displayName = "DotCode",
            zintSymbolId = 115,
            zintConstantName = "BARCODE_DOTCODE",
            readerFormat = null,
            dimension = Dimension.MATRIX,
            category = Category.INDUSTRIAL,
            charsetRule = CharsetRule.AnyByte,
            lengthRule = LengthRule.UpTo(620),
            checkDigit = CheckDigitBehaviour.NONE,
            supportsGs1 = true,
            supportsEci = true,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "DotCode",
            notes = "Generate only: the reader engine cannot decode DotCode. " +
                "Rendered as dots rather than squares.",
        ),
        SymbologySpec(
            id = SymbologyId.MAXICODE,
            displayName = "MaxiCode",
            zintSymbolId = 57,
            zintConstantName = "BARCODE_MAXICODE",
            readerFormat = "MAXI_CODE",
            dimension = Dimension.MATRIX,
            category = Category.LOGISTICS,
            charsetRule = CharsetRule.AnyByte,
            lengthRule = LengthRule.UpTo(93),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = false,
            supportsEci = true,
            supportsStructuredAppend = true,
            supportsCodesetEscapes = false,
            sampleValue = "MaxiCode payload",
            notes = "Fixed size with a hexagonal module grid and central bullseye; " +
                "needs a dedicated renderer path.",
        ),

        // ---- Linear, general purpose ----
        SymbologySpec(
            id = SymbologyId.CODE_128,
            displayName = "Code 128",
            zintSymbolId = 20,
            zintConstantName = "BARCODE_CODE128",
            readerFormat = "CODE_128",
            dimension = Dimension.LINEAR,
            category = Category.GENERAL,
            charsetRule = CharsetRule.FullAscii,
            lengthRule = LengthRule.UpTo(99),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = false,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = true,
            sampleValue = "ABC123",
            notes = "Supports manual codeset switching and FNC1-FNC4 insertion.",
        ),
        SymbologySpec(
            id = SymbologyId.GS1_128,
            displayName = "GS1-128",
            zintSymbolId = 16,
            zintConstantName = "BARCODE_GS1_128",
            readerFormat = "CODE_128",
            dimension = Dimension.LINEAR,
            category = Category.GS1,
            charsetRule = CharsetRule.PrintableAscii,
            lengthRule = LengthRule.UpTo(99),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = true,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = true,
            sampleValue = "[01]09501101530003",
            notes = "Application Identifiers in brackets; FNC1 separators are automatic.",
        ),
        SymbologySpec(
            id = SymbologyId.CODE_39,
            displayName = "Code 39",
            zintSymbolId = 8,
            zintConstantName = "BARCODE_CODE39",
            readerFormat = "CODE_39",
            dimension = Dimension.LINEAR,
            category = Category.INDUSTRIAL,
            charsetRule = CODE39_CHARS,
            lengthRule = LengthRule.Range(1, 85),
            checkDigit = CheckDigitBehaviour.OPTIONAL,
            supportsGs1 = false,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "CODE39",
            notes = "Uppercase only. Use Extended Code 39 for the full ASCII range.",
        ),
        SymbologySpec(
            id = SymbologyId.CODE_93,
            displayName = "Code 93",
            zintSymbolId = 25,
            zintConstantName = "BARCODE_CODE93",
            readerFormat = "CODE_93",
            dimension = Dimension.LINEAR,
            category = Category.INDUSTRIAL,
            charsetRule = CharsetRule.FullAscii,
            lengthRule = LengthRule.Range(1, 123),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = false,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "CODE93",
        ),
        SymbologySpec(
            id = SymbologyId.CODABAR,
            displayName = "Codabar",
            zintSymbolId = 18,
            zintConstantName = "BARCODE_CODABAR",
            readerFormat = "CODABAR",
            dimension = Dimension.LINEAR,
            category = Category.INDUSTRIAL,
            charsetRule = CODABAR_CHARS,
            lengthRule = LengthRule.Range(3, 60),
            checkDigit = CheckDigitBehaviour.OPTIONAL,
            supportsGs1 = false,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "A123456B",
            notes = "Requires A-D start and stop characters.",
        ),
        SymbologySpec(
            id = SymbologyId.CODE_11,
            displayName = "Code 11",
            zintSymbolId = 1,
            zintConstantName = "BARCODE_CODE11",
            readerFormat = null,
            dimension = Dimension.LINEAR,
            category = Category.INDUSTRIAL,
            charsetRule = CharsetRule.Chars("0123456789-", "Digits and hyphen"),
            lengthRule = LengthRule.Range(1, 140),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = false,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "123-456",
            notes = "Generate only: not in the reader engine's format set.",
        ),
        SymbologySpec(
            id = SymbologyId.MSI_PLESSEY,
            displayName = "MSI Plessey",
            zintSymbolId = 47,
            zintConstantName = "BARCODE_MSI_PLESSEY",
            readerFormat = null,
            dimension = Dimension.LINEAR,
            category = Category.INDUSTRIAL,
            charsetRule = CharsetRule.Numeric,
            lengthRule = LengthRule.Range(1, 65),
            checkDigit = CheckDigitBehaviour.OPTIONAL,
            supportsGs1 = false,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "1234567890",
            notes = "Generate only: not in the reader engine's format set.",
        ),
        SymbologySpec(
            id = SymbologyId.TELEPEN,
            displayName = "Telepen Alpha",
            zintSymbolId = 32,
            zintConstantName = "BARCODE_TELEPEN",
            readerFormat = "TELEPEN",
            dimension = Dimension.LINEAR,
            category = Category.INDUSTRIAL,
            charsetRule = CharsetRule.FullAscii,
            lengthRule = LengthRule.Range(1, 30),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = false,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "TELEPEN",
        ),

        // ---- Linear, retail and logistics ----
        SymbologySpec(
            id = SymbologyId.EAN_13,
            displayName = "EAN-13",
            zintSymbolId = 15,
            zintConstantName = "BARCODE_EAN13",
            readerFormat = "EAN_13",
            dimension = Dimension.LINEAR,
            category = Category.RETAIL,
            charsetRule = CharsetRule.Numeric,
            lengthRule = LengthRule.Exact(setOf(12, 13)),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = false,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "012345678901",
            notes = "Supply 12 digits and the check digit is computed, or 13 to validate it.",
        ),
        SymbologySpec(
            id = SymbologyId.EAN_8,
            displayName = "EAN-8",
            zintSymbolId = 10,
            zintConstantName = "BARCODE_EAN8",
            readerFormat = "EAN_8",
            dimension = Dimension.LINEAR,
            category = Category.RETAIL,
            charsetRule = CharsetRule.Numeric,
            lengthRule = LengthRule.Exact(setOf(7, 8)),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = false,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "1234567",
        ),
        SymbologySpec(
            id = SymbologyId.UPC_A,
            displayName = "UPC-A",
            zintSymbolId = 34,
            zintConstantName = "BARCODE_UPCA",
            readerFormat = "UPC_A",
            dimension = Dimension.LINEAR,
            category = Category.RETAIL,
            charsetRule = CharsetRule.Numeric,
            lengthRule = LengthRule.Exact(setOf(11, 12)),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = false,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "01234567891",
        ),
        SymbologySpec(
            id = SymbologyId.UPC_E,
            displayName = "UPC-E",
            zintSymbolId = 37,
            zintConstantName = "BARCODE_UPCE",
            readerFormat = "UPC_E",
            dimension = Dimension.LINEAR,
            category = Category.RETAIL,
            charsetRule = CharsetRule.Numeric,
            lengthRule = LengthRule.Exact(setOf(6, 7, 8)),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = false,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "0425261",
        ),
        SymbologySpec(
            id = SymbologyId.ITF,
            displayName = "Interleaved 2 of 5",
            zintSymbolId = 3,
            zintConstantName = "BARCODE_C25INTER",
            readerFormat = "ITF",
            dimension = Dimension.LINEAR,
            category = Category.LOGISTICS,
            charsetRule = CharsetRule.Numeric,
            lengthRule = LengthRule.EvenPairs(1, 45),
            checkDigit = CheckDigitBehaviour.OPTIONAL,
            supportsGs1 = false,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "1234567890",
            notes = "Encodes digits in pairs, so an even count is required.",
        ),
        SymbologySpec(
            id = SymbologyId.ITF_14,
            displayName = "ITF-14",
            zintSymbolId = 89,
            zintConstantName = "BARCODE_ITF14",
            readerFormat = "ITF_14",
            dimension = Dimension.LINEAR,
            category = Category.LOGISTICS,
            charsetRule = CharsetRule.Numeric,
            lengthRule = LengthRule.Exact(setOf(13, 14)),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = false,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "0950110153000",
            notes = "Shipping-container GTIN-14, drawn with a heavy bearer bar.",
        ),

        // ---- GS1 DataBar ----
        SymbologySpec(
            id = SymbologyId.DATABAR_OMNI,
            displayName = "GS1 DataBar Omnidirectional",
            zintSymbolId = 29,
            zintConstantName = "BARCODE_DBAR_OMN",
            readerFormat = "DATA_BAR",
            dimension = Dimension.LINEAR,
            category = Category.GS1,
            charsetRule = CharsetRule.Numeric,
            lengthRule = LengthRule.Exact(setOf(13, 14)),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = true,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "0950110153000",
        ),
        SymbologySpec(
            id = SymbologyId.DATABAR_LIMITED,
            displayName = "GS1 DataBar Limited",
            zintSymbolId = 30,
            zintConstantName = "BARCODE_DBAR_LTD",
            readerFormat = "DATA_BAR_LTD",
            dimension = Dimension.LINEAR,
            category = Category.GS1,
            charsetRule = CharsetRule.Numeric,
            lengthRule = LengthRule.Exact(setOf(13, 14)),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = true,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "0950110153000",
            notes = "Restricted to indicator digits 0 and 1.",
        ),
        SymbologySpec(
            id = SymbologyId.DATABAR_EXPANDED,
            displayName = "GS1 DataBar Expanded",
            zintSymbolId = 31,
            zintConstantName = "BARCODE_DBAR_EXP",
            readerFormat = "DATA_BAR_EXP",
            dimension = Dimension.LINEAR,
            category = Category.GS1,
            charsetRule = CharsetRule.PrintableAscii,
            lengthRule = LengthRule.UpTo(74),
            checkDigit = CheckDigitBehaviour.AUTOMATIC,
            supportsGs1 = true,
            supportsEci = false,
            supportsStructuredAppend = false,
            supportsCodesetEscapes = false,
            sampleValue = "[01]09501101530003",
        ),
    )

    private val byId: Map<SymbologyId, SymbologySpec> = all.associateBy { it.id }

    operator fun get(id: SymbologyId): SymbologySpec =
        byId[id] ?: error("Symbology $id missing from registry")

    fun find(id: SymbologyId): SymbologySpec? = byId[id]

    /** Formats the scanner can be asked to decode. */
    val readable: List<SymbologySpec> = all.filter { it.isReadable }

    /** Formats that can only be produced, never scanned. */
    val generateOnly: List<SymbologySpec> = all.filterNot { it.isReadable }

    fun byCategory(category: Category): List<SymbologySpec> =
        all.filter { it.category == category }

    fun byDimension(dimension: Dimension): List<SymbologySpec> =
        all.filter { it.dimension == dimension }
}
